#!/bin/bash
#echo "Hello Devops" > "\\*\\\\'\"DevOps\"\\'\\\\*\$\\?\\*\\*\\*\\*\\*:)"
#echo "Hello Devops" > "\*\\\\'\"DevOps\"\'\\*\$\?\*\*\*\*\*:)"
printf "Hello Devops\n" > \\\*\\\\\'\"DevOps\"\\\'\\\\\*\$\\\?\\\*\\\*\\\*\\\*\\\*\:\)

