#!/bin/bash
#echo "Hello Devops" > "\\*\\\\'\"DevOps\"\\'\\\\*\$\\?\\*\\*\\*\\*\\*:)"
#echo "Hello Devops" > "\*\\\\'\"DevOps\"\'\\*\$\?\*\*\*\*\*:)"
echo "Hello Devops" > \\\*\\\\\'\"DevOps\"\\\'\\\\\*\$\\\?\\\*\\\*\\\*\\\*\\\*\:\)

